version: '3'

services:
  backend:
    build: ./
    container_name: nestjs-backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - database
      - redis_queue
    networks:
      - nestjs_network
  database:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - './mongodb-backup:/data/db'
    networks:
      - nestjs_network
  redis_queue:
    image: redis:alpine
    container_name: redis_queue
    volumes:
      - "/data"
    ports:
      - '6379:6379'
    networks:
      - nestjs_network

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    volumes:
      - "./redisinsight:/data"
    ports:
      - '5540:5540'
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge