name: Basic deploy
on:
  push:
    branches: [ master ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: eu-north-1

          aws_elb_app_port: 3000 # This should match the docker exposed port. Defaults to 3000.